export const ICONS = {
  TOPICS: "TOPICS",
  POSTS: "POSTS",
  REPLIES: "REPLIES",
  BALLOON: "BALLOON",
  BALLOONS: "BALLOONS",
  TIME: "TIME",
  THUMBS_UP: "THUMBS_UP",
  THUMBS_DOWN: "THUMBS_DOWN"
};

export const ACTIONS = {
  SET_POSTS: "SET_POSTS",
  SET_CATEGORIES: "SET_CATEGORIES",
  UP_VOTE: "UP_VOTE",
  UP_VOTE_COMMENTS: "UP_VOTE_COMMENTS",
  DOWN_VOTE_COMMENTS: "DOWN_VOTE_COMMENTS",
  DOWN_VOTE: "DOWN_VOTE",
  SET_COMMENTS_POST: "SET_COMMENTS_POST",
  ADD_COMMENT: "ADD_COMMENT",
  UPDATE_POSTS: "UPDATE_POSTS",
  UPDATE_UNIQUE_POST: "UPDATE_UNIQUE_POST",
  ADD_POST: "ADD_POST",
  ORDER_BY: "ORDER_BY",
  UPDATE_COMMENT: "UPDATE_COMMENT",
  DEL_COMMENT: "DEL_COMMENT",
  DEL_POST: "DEL_POST"
};

export const TYPE_CONTEXT = {
  POST: "POST",
  COMMENT: "COMMENT"
};
