export const ICONS = {
  TOPICS: "TOPICS",
  POSTS: "POSTS",
  REPLIES: "REPLIES",
  BALLOON: "BALLOON",
  BALLOONS: "BALLOONS",
  TIME: "TIME",
  THUMBS_UP: "THUMBS_UP",
  THUMBS_DOWN: "THUMBS_DOWN"
};

export const ACTIONS = {
  SET_POSTS: "SET_POSTS",
  SET_CATEGORIES: "SET_CATEGORIES",
  UP_VOTE: "UP_VOTE",
  DOWN_VOTE: "DOWN_VOTE",
  SET_COMMENTS_POST: "SET_COMMENTS_POST"
};
